-- Genres
INSERT INTO genre(id,name,description) VALUES (1,'Hip-Hop','Rap and hip-hop music');
INSERT INTO genre(id,name,description) VALUES (2,'Pop','Popular music');
INSERT INTO genre(id,name,description) VALUES (3,'Rock','Rock music');
INSERT INTO genre(id,name,description) VALUES (4,'R&B','Rhythm and Blues');
INSERT INTO genre(id,name,description) VALUES (5,'Jazz','Jazz music');
INSERT INTO genre(id,name,description) VALUES (6,'Classical','Classical compositions');
INSERT INTO genre(id,name,description) VALUES (7,'EDM','Electronic Dance Music');
INSERT INTO genre(id,name,description) VALUES (8,'Country','Country music');
INSERT INTO genre(id,name,description) VALUES (9,'Indie','Independent music');
INSERT INTO genre(id,name,description) VALUES (10,'Lo-fi','Lo-fi chill music');

-- Users
INSERT INTO users(id,username,email,password,role,enabled) VALUES (1,'admin','admin@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','ADMIN',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (2,'eminem','artist1@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','ARTIST',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (3,'theweeknd','artist2@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','ARTIST',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (4,'drake','artist3@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','ARTIST',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (5,'taylorswift','artist4@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','ARTIST',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (6,'imaginedragons','artist5@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','ARTIST',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (7,'dualipa','artist6@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','ARTIST',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (8,'postmalone','artist7@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','ARTIST',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (9,'arijitsingh','artist8@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','ARTIST',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (10,'user1','user1@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','USER',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (11,'user2','user2@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','USER',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (12,'user3','user3@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','USER',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (13,'user4','user4@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','USER',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (14,'user5','user5@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','USER',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (15,'user6','user6@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','USER',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (16,'user7','user7@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','USER',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (17,'user8','user8@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','USER',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (18,'user9','user9@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','USER',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (19,'user10','user10@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','USER',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (20,'user11','user11@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','USER',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (21,'user12','user12@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','USER',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (22,'user13','user13@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','USER',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (23,'user14','user14@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','USER',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (24,'user15','user15@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','USER',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (25,'user16','user16@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','USER',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (26,'user17','user17@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','USER',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (27,'user18','user18@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','USER',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (28,'user19','user19@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','USER',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (29,'user20','user20@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','USER',1);
INSERT INTO users(id,username,email,password,role,enabled) VALUES (30,'user21','user21@example.com','$2a$10$.fB1Izk5tCV5JMW7CE.biuCY/VlRZ8SzTsRH4RTAOiG8C.Am.7AbC','USER',1);

-- Artists
INSERT INTO artist(id,name,bio,country) VALUES (1,'Eminem','Artist biography','USA');
INSERT INTO artist(id,name,bio,country) VALUES (2,'The Weeknd','Artist biography','USA');
INSERT INTO artist(id,name,bio,country) VALUES (3,'Drake','Artist biography','USA');
INSERT INTO artist(id,name,bio,country) VALUES (4,'Taylor Swift','Artist biography','USA');
INSERT INTO artist(id,name,bio,country) VALUES (5,'Imagine Dragons','Artist biography','USA');
INSERT INTO artist(id,name,bio,country) VALUES (6,'Dua Lipa','Artist biography','USA');
INSERT INTO artist(id,name,bio,country) VALUES (7,'Post Malone','Artist biography','USA');
INSERT INTO artist(id,name,bio,country) VALUES (8,'Arijit Singh','Artist biography','USA');
INSERT INTO artist(id,name,bio,country) VALUES (9,'Shreya Ghoshal','Artist biography','USA');
INSERT INTO artist(id,name,bio,country) VALUES (10,'Alan Walker','Artist biography','USA');

-- Albums
INSERT INTO album(id,title,description,release_date,artist_id) VALUES (1,'Eminem Essentials','Popular tracks','2021-01-01',1);
INSERT INTO album(id,title,description,release_date,artist_id) VALUES (2,'The Weeknd Essentials','Popular tracks','2022-01-01',2);
INSERT INTO album(id,title,description,release_date,artist_id) VALUES (3,'Drake Essentials','Popular tracks','2023-01-01',3);
INSERT INTO album(id,title,description,release_date,artist_id) VALUES (4,'Taylor Swift Essentials','Popular tracks','2024-01-01',4);
INSERT INTO album(id,title,description,release_date,artist_id) VALUES (5,'Imagine Dragons Essentials','Popular tracks','2025-01-01',5);
INSERT INTO album(id,title,description,release_date,artist_id) VALUES (6,'Dua Lipa Essentials','Popular tracks','2026-01-01',6);
INSERT INTO album(id,title,description,release_date,artist_id) VALUES (7,'Post Malone Essentials','Popular tracks','2027-01-01',7);
INSERT INTO album(id,title,description,release_date,artist_id) VALUES (8,'Arijit Singh Essentials','Popular tracks','2028-01-01',8);
INSERT INTO album(id,title,description,release_date,artist_id) VALUES (9,'Shreya Ghoshal Essentials','Popular tracks','2029-01-01',9);
INSERT INTO album(id,title,description,release_date,artist_id) VALUES (10,'Alan Walker Essentials','Popular tracks','2020-01-01',10);

-- Songs
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (1,'Eminem Track 1',180,'2020-01-01','ENGLISH',1,1,1000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (2,'Eminem Track 2',190,'2021-01-01','ENGLISH',1,1,2000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (3,'Eminem Track 3',200,'2022-01-01','ENGLISH',1,1,3000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (4,'Eminem Track 4',210,'2023-01-01','ENGLISH',1,1,4000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (5,'The Weeknd Track 1',180,'2020-01-01','ENGLISH',2,2,5000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (6,'The Weeknd Track 2',190,'2021-01-01','ENGLISH',2,2,6000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (7,'The Weeknd Track 3',200,'2022-01-01','ENGLISH',2,2,7000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (8,'The Weeknd Track 4',210,'2023-01-01','ENGLISH',2,2,8000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (9,'Drake Track 1',180,'2020-01-01','ENGLISH',3,3,9000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (10,'Drake Track 2',190,'2021-01-01','ENGLISH',3,3,10000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (11,'Drake Track 3',200,'2022-01-01','ENGLISH',3,3,11000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (12,'Drake Track 4',210,'2023-01-01','ENGLISH',3,3,12000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (13,'Taylor Swift Track 1',180,'2020-01-01','ENGLISH',4,4,13000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (14,'Taylor Swift Track 2',190,'2021-01-01','ENGLISH',4,4,14000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (15,'Taylor Swift Track 3',200,'2022-01-01','ENGLISH',4,4,15000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (16,'Taylor Swift Track 4',210,'2023-01-01','ENGLISH',4,4,16000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (17,'Imagine Dragons Track 1',180,'2020-01-01','ENGLISH',5,5,17000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (18,'Imagine Dragons Track 2',190,'2021-01-01','ENGLISH',5,5,18000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (19,'Imagine Dragons Track 3',200,'2022-01-01','ENGLISH',5,5,19000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (20,'Imagine Dragons Track 4',210,'2023-01-01','ENGLISH',5,5,20000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (21,'Dua Lipa Track 1',180,'2020-01-01','ENGLISH',6,6,21000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (22,'Dua Lipa Track 2',190,'2021-01-01','ENGLISH',6,6,22000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (23,'Dua Lipa Track 3',200,'2022-01-01','ENGLISH',6,6,23000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (24,'Dua Lipa Track 4',210,'2023-01-01','ENGLISH',6,6,24000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (25,'Post Malone Track 1',180,'2020-01-01','ENGLISH',7,7,25000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (26,'Post Malone Track 2',190,'2021-01-01','ENGLISH',7,7,26000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (27,'Post Malone Track 3',200,'2022-01-01','ENGLISH',7,7,27000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (28,'Post Malone Track 4',210,'2023-01-01','ENGLISH',7,7,28000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (29,'Arijit Singh Track 1',180,'2020-01-01','HINDI',8,8,29000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (30,'Arijit Singh Track 2',190,'2021-01-01','HINDI',8,8,30000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (31,'Arijit Singh Track 3',200,'2022-01-01','HINDI',8,8,31000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (32,'Arijit Singh Track 4',210,'2023-01-01','HINDI',8,8,32000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (33,'Shreya Ghoshal Track 1',180,'2020-01-01','HINDI',9,9,33000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (34,'Shreya Ghoshal Track 2',190,'2021-01-01','HINDI',9,9,34000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (35,'Shreya Ghoshal Track 3',200,'2022-01-01','HINDI',9,9,35000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (36,'Shreya Ghoshal Track 4',210,'2023-01-01','HINDI',9,9,36000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (37,'Alan Walker Track 1',180,'2020-01-01','HINDI',10,10,37000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (38,'Alan Walker Track 2',190,'2021-01-01','HINDI',10,10,38000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (39,'Alan Walker Track 3',200,'2022-01-01','HINDI',10,10,39000);
INSERT INTO song(id,title,duration,release_date,language,genre_id,album_id,play_count) VALUES (40,'Alan Walker Track 4',210,'2023-01-01','HINDI',10,10,40000);

-- Artist_Song
INSERT INTO artist_song(artist_id,song_id) VALUES (1,1);
INSERT INTO artist_song(artist_id,song_id) VALUES (1,2);
INSERT INTO artist_song(artist_id,song_id) VALUES (1,3);
INSERT INTO artist_song(artist_id,song_id) VALUES (1,4);
INSERT INTO artist_song(artist_id,song_id) VALUES (2,5);
INSERT INTO artist_song(artist_id,song_id) VALUES (2,6);
INSERT INTO artist_song(artist_id,song_id) VALUES (2,7);
INSERT INTO artist_song(artist_id,song_id) VALUES (2,8);
INSERT INTO artist_song(artist_id,song_id) VALUES (3,9);
INSERT INTO artist_song(artist_id,song_id) VALUES (3,10);
INSERT INTO artist_song(artist_id,song_id) VALUES (3,11);
INSERT INTO artist_song(artist_id,song_id) VALUES (3,12);
INSERT INTO artist_song(artist_id,song_id) VALUES (4,13);
INSERT INTO artist_song(artist_id,song_id) VALUES (4,14);
INSERT INTO artist_song(artist_id,song_id) VALUES (4,15);
INSERT INTO artist_song(artist_id,song_id) VALUES (4,16);
INSERT INTO artist_song(artist_id,song_id) VALUES (5,17);
INSERT INTO artist_song(artist_id,song_id) VALUES (5,18);
INSERT INTO artist_song(artist_id,song_id) VALUES (5,19);
INSERT INTO artist_song(artist_id,song_id) VALUES (5,20);
INSERT INTO artist_song(artist_id,song_id) VALUES (6,21);
INSERT INTO artist_song(artist_id,song_id) VALUES (6,22);
INSERT INTO artist_song(artist_id,song_id) VALUES (6,23);
INSERT INTO artist_song(artist_id,song_id) VALUES (6,24);
INSERT INTO artist_song(artist_id,song_id) VALUES (7,25);
INSERT INTO artist_song(artist_id,song_id) VALUES (7,26);
INSERT INTO artist_song(artist_id,song_id) VALUES (7,27);
INSERT INTO artist_song(artist_id,song_id) VALUES (7,28);
INSERT INTO artist_song(artist_id,song_id) VALUES (8,29);
INSERT INTO artist_song(artist_id,song_id) VALUES (8,30);
INSERT INTO artist_song(artist_id,song_id) VALUES (8,31);
INSERT INTO artist_song(artist_id,song_id) VALUES (8,32);
INSERT INTO artist_song(artist_id,song_id) VALUES (9,33);
INSERT INTO artist_song(artist_id,song_id) VALUES (9,34);
INSERT INTO artist_song(artist_id,song_id) VALUES (9,35);
INSERT INTO artist_song(artist_id,song_id) VALUES (9,36);
INSERT INTO artist_song(artist_id,song_id) VALUES (10,37);
INSERT INTO artist_song(artist_id,song_id) VALUES (10,38);
INSERT INTO artist_song(artist_id,song_id) VALUES (10,39);
INSERT INTO artist_song(artist_id,song_id) VALUES (10,40);